// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBeh79v1Hszuz7Lz3zCpXb1UNDh4MCq_g',
    appId: '1:584269991138:web:4b5b11ddff3bc1584da2bb',
    messagingSenderId: '584269991138',
    projectId: 'lifetimedesign-23c6a',
    authDomain: 'lifetimedesign-23c6a.firebaseapp.com',
    storageBucket: 'lifetimedesign-23c6a.appspot.com',
    measurementId: 'G-6ZQLM7HCN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpTM-GLCFoQ5NqNAYWDXvLSPv7zqTAGY',
    appId: '1:584269991138:android:1f62c358b55738d04da2bb',
    messagingSenderId: '584269991138',
    projectId: 'lifetimedesign-23c6a',
    storageBucket: 'lifetimedesign-23c6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF1JZhLrRqqCg3m4qYsC_NYbGV4UW2IDk',
    appId: '1:584269991138:ios:896acc85b52c60a44da2bb',
    messagingSenderId: '584269991138',
    projectId: 'lifetimedesign-23c6a',
    storageBucket: 'lifetimedesign-23c6a.appspot.com',
    iosBundleId: 'com.example.ldReceipUploader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF1JZhLrRqqCg3m4qYsC_NYbGV4UW2IDk',
    appId: '1:584269991138:ios:896acc85b52c60a44da2bb',
    messagingSenderId: '584269991138',
    projectId: 'lifetimedesign-23c6a',
    storageBucket: 'lifetimedesign-23c6a.appspot.com',
    iosBundleId: 'com.example.ldReceipUploader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBeh79v1Hszuz7Lz3zCpXb1UNDh4MCq_g',
    appId: '1:584269991138:web:d21c3f81884ea39f4da2bb',
    messagingSenderId: '584269991138',
    projectId: 'lifetimedesign-23c6a',
    authDomain: 'lifetimedesign-23c6a.firebaseapp.com',
    storageBucket: 'lifetimedesign-23c6a.appspot.com',
    measurementId: 'G-292CVRZGC8',
  );
}